name: Build Installer

on:
    push:
        branches:
            - main
    workflow_dispatch:

jobs:
    build:
        runs-on: windows-latest

        steps:
              - name: Checkout repository
                uses: actions/checkout@v4
    
              - name: Download favicon.png
                run: |
                  Invoke-WebRequest -Uri "https://mbf.bsquest.xyz/favicon.png" -OutFile "favicon.png"
                shell: pwsh

              - name: Install ps2exe
                run: Install-Module -Name ps2exe -Force -Scope CurrentUser -AllowClobber
                shell: pwsh

              - name: Install ImageMagick
                run: choco install imagemagick --yes
                shell: pwsh
    
              - name: Convert the PNG to an Icon using ImageMagick
                run: magick convert favicon.png favicon.ico


              - name: Compile installer.ps1 to installer.exe
                run: |
                  Invoke-ps2exe -inputFile .\installer.ps1 -outputFile .\MBF-Bridge-Installer.exe -verbose -iconFile .\favicon.ico -noConsole
                shell: pwsh
    
              - name: Upload installer.exe as artifact
                uses: actions/upload-artifact@v4
                with:
                  name: MBF-Bridge-Installer
                  path: MBF-Bridge-Installer.exe

    release:
        runs-on: ubuntu-latest
        needs: build
        steps:
              - name: Checkout repository
                uses: actions/checkout@v4
    
              - name: Extract version and release notes from commit message
                id: extract_version
                run: |
                  COMMIT_MESSAGE=$(git log -1 --pretty=%B)
                  if [[ "$COMMIT_MESSAGE" =~ ^v([0-9]+\.[0-9]+\.[0-9]+) ]]; then
                    VERSION="${BASH_REMATCH[1]}"
                    RELEASE_NOTES=$(echo "$COMMIT_MESSAGE" | sed -e "1d")
                    echo "::set-output name=version::$VERSION"
                    echo "::set-output name=release_notes::$RELEASE_NOTES"
                  else
                    echo "No version tag found in commit message."
                    exit 0
                  fi
                shell: bash
    
              - name: Create GitHub Release
                if: steps.extract_version.outputs.version != ''
                uses: actions/create-release@v1
                with:
                  tag_name: ${{ steps.extract_version.outputs.version }}
                  release_name: Release ${{ steps.extract_version.outputs.version }}
                  body: ${{ steps.extract_version.outputs.release_notes }}
                env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
              - name: Upload installer to release
                if: env.version != ''
                uses: actions/upload-release-asset@v1
                with:
                  upload_url: ${{ steps.create-release.outputs.upload_url }}
                  asset_path: ./MBF-Bridge-Installer.exe
                  asset_name: MBF-Bridge-Installer.exe
                  asset_content_type: application/octet-stream
