name: Build Installer

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download favicon.png
        run: |
          Invoke-WebRequest -Uri "https://mbf.bsquest.xyz/favicon.png" -OutFile "favicon.png"
        shell: pwsh

      - name: Convert PNG to ICO
        run: |
          Add-Type -AssemblyName System.Drawing
          $image = [System.Drawing.Image]::FromFile("favicon.png")
          $icon = New-Object System.Drawing.Icon ([System.IO.MemoryStream]::new())
          $stream = [System.IO.MemoryStream]::new()
          $image.Save($stream, [System.Drawing.Imaging.ImageFormat]::Png)
          $stream.Position = 0
          $bitmap = New-Object System.Drawing.Bitmap ($stream)
          $icon = [System.Drawing.Icon]::FromHandle($bitmap.GetHicon())
          $fileStream = [System.IO.File]::Create("favicon.ico")
          $icon.Save($fileStream)
          $fileStream.Close()
        shell: pwsh

      - name: Install ps2exe
        run: Install-Module -Name ps2exe -Force -Scope CurrentUser -AllowClobber
        shell: pwsh

      - name: Compile installer.ps1 to installer.exe
        run: |
          Invoke-ps2exe .\installer.ps1 .\installer.exe -noConsole
        shell: pwsh

      - name: Upload installer.exe as artifact
        uses: actions/upload-artifact@v3
        with:
          name: installer
          path: installer.exe
